### PR TITLE
deal with hook

### PR DESCRIPTION
**Pull request by laishulu**

### CODE REVIEW

**Comment by brahma-dev** [comment]
It would be nice if you can add an example for this in the README, I can merge this then.

**Comment by laishulu** [comment]
> It would be nice if you can add an example for this in the README, I can merge this then.

Already in README, please check:

CleanShot 2024-11-21 at 23 02 46@2x

**Comment by brahma-dev** [comment]
Sorry, I meant a docker compose example. One with a sample nginx and appropriate mounts.

**Comment by laishulu** [comment]
Do you mean something like this?
```
❯ cat compose.yml
services:
  lego:
    image: acme-lego-cron:latest
    container_name: lego
    env_file:
      - .env
    volumes:
      - "../cert:/letsencrypt"
      - "./docker:/bin/docker"
      - "./hooks:/hooks"
    restart: always
```

**Pull request merged**
